name: compiler_dart
description: A sample command-line application.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.1.1

# Add regular dependencies here.
dependencies:
  fixnum: ^1.1.0

dev_dependencies:
  lint: ^2.1.2
  path: ^1.8.3
  test: ^1.21.0
